# Generated by Django 5.1.4 on 2025-03-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="full_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="projects",
            name="git_hub",
            field=models.URLField(
                blank=True,
                default="https://www.linkedin.com/in/merlijn-wolters-0b3450140/",
            ),
        ),
    ]
