# Generated by Django 5.1.4 on 2025-03-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_coverletter_refrences"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coverletter",
            old_name="name",
            new_name="my_name",
        ),
        migrations.RenameField(
            model_name="refrences",
            old_name="name",
            new_name="ref_name",
        ),
        migrations.AlterField(
            model_name="coverletter",
            name="coverletter",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="refrences",
            name="date",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="refrences",
            name="refrence",
            field=models.TextField(blank=True),
        ),
    ]
