# Generated by Django 5.1.7 on 2025-03-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_rename_name_coverletter_my_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Webinfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("webinfo", models.TextField(blank=True)),
            ],
        ),
    ]
