# Generated by Django 5.1.7 on 2025-03-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_webinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="webinfo",
            name="webliner",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
