# Generated by Django 5.2.1 on 2025-05-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_coverletter_picture_alter_cv_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverletter',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
